dqn:
  CartPole-v0:
    algo_name: dqn
    learning_rate: 0.01
    max_timesteps: 20000
    buffer_size: 10000
    batch_size: 64
    logger: tensorboard

  CartPole-v1:
    algo_name: dqn
    learning_rate: 0.01
    min_learning_rate: 1.0e-5
    max_timesteps: 100000
    buffer_size: 10000
    batch_size: 64
    n_steps: 3

double_dqn:
  CartPole-v0:
    algo_name: ddqn
    learning_rate: 0.01
    max_timesteps: 20000
    buffer_size: 10000
    batch_size: 64
    double_dqn: True

  CartPole-v1:
    algo_name: ddqn
    learning_rate: 0.01
    min_learning_rate: 1.0e-5
    max_timesteps: 100000
    buffer_size: 10000
    batch_size: 64
    double_dqn: True
    n_steps: 3

dueling_dqn:
  CartPole-v0:
    algo_name: dueling_dqn
    learning_rate: 0.01
    max_timesteps: 20000
    buffer_size: 10000
    batch_size: 64
    dueling_dqn : True
    double_dqn: True

  CartPole-v1:
    algo_name: dueling_dqn
    learning_rate: 0.01
    max_timesteps: 100000
    buffer_size: 10000
    batch_size: 64
    dueling_dqn : True
    double_dqn: True
    n_steps: 3

noisy_dqn:
  CartPole-v0:
    algo_name: noisy_dqn
    learning_rate: 0.05
    max_timesteps: 30000
    buffer_size: 10000
    batch_size: 64
    double_dqn: True
    noisy_dqn: True
    train_frequency: 20
    learn_steps: 2
    target_update_frequency: 100
    logger: tensorboard

  CartPole-v1:
    algo_name: noisy_dqn
    learning_rate: 0.01
    max_timesteps: 100000
    buffer_size: 10000
    batch_size: 64
    noisy_dqn: True
    logger: tensorboard

categorical_dqn:
  CartPole-v0:
    algo_name: categorical_dqn
    learning_rate: 0.05
    max_timesteps: 20000
    buffer_size: 10000
    batch_size: 128
    train_frequency: 20
    learn_steps: 2
    n_steps: 1
    target_update_frequency: 100
    logger: tensorboard

per:
  CartPole-v0:
    algo_name: per
    double_dqn: True
    learning_rate: 0.01
    max_timesteps: 20000
    buffer_size: 10000
    train_frequency: 10
    learn_steps: 2
    target_update_frequency: 50
    batch_size: 64
    logger: tensorboard

  CartPole-v1:
    algo_name: per
    learning_rate: 0.01
    min_learning_rate: 1.0e-5
    max_timesteps: 200000
    buffer_size: 10000
    train_frequency: 20
    learn_steps: 1
    target_update_frequency: 100
    batch_size: 64
    logger: tensorboard

rainbow:
  CartPole-v0:
    algo_name: rainbow
    learning_rate: 0.05
    max_timesteps: 20000
    buffer_size: 10000
    batch_size: 128
    train_frequency: 20
    learn_steps: 2
    n_steps: 1
    target_update_frequency: 100
    logger: tensorboard

  CartPole-v1:
    algo_name: per
    learning_rate: 0.01
    min_learning_rate: 1.0e-5
    max_timesteps: 100000
    buffer_size: 10000
    target_update_frequency: 1000
    batch_size: 64
    logger: tensorboard

c51:
  CartPole-v0:
    algo_name: c51
    learning_rate: 1.0e-4
    max_timesteps: 30000
    buffer_size: 10000
    target_update_frequency: 100
    train_frequency: 10
    gradient_steps: 5
    batch_size: 128

ddpg:
  Pendulum-v1:
    algo_name: ddpg
    actor_lr: 1.0e-2
    critic_lr: 1.0e-3
    max_timesteps: 200000
    buffer_size: 20000
    use_smooth_l1_loss: True
    target_update_frequency: 1
    soft_update_tau: 0.01
    train_frequency: 10
    gradient_steps: 5
    batch_size: 256
    logger: tensorboard

a2c:
  CartPole-v0:
    algo_name: a2c
    max_timesteps: 50000
    learning_rate: 0.001
    buffer_size: 128
    rollout_steps: 128
    batch_size: 64
    update_epochs: 5
    logger: tensorboard

  CartPole-v1:
    algo_name: a2c
    max_timesteps: 300000
    learning_rate: 1.0e-3
    buffer_size: 128
    rollout_steps: 128
    batch_size: 32
    logger: tensorboard


ppo_clip:
  CartPole-v0:
    algo_name: ppo_clip
    max_timesteps: 50000
    learning_rate: 1.0e-3
    buffer_size: 128
    rollout_steps: 128
    batch_size: 32
    logger: wandb

  CartPole-v1:
    algo_name: ppo_clip
    max_timesteps: 300000
    learning_rate: 1.0e-3
    buffer_size: 128
    rollout_steps: 128
    batch_size: 32
    logger: wandb

ppo_penalty:
  CartPole-v0:
    algo_name: ppo_penalty
    max_timesteps: 50000
    actor_lr: 1.0e-3
    critic_lr: 1.0e-2
    buffer_size: 128
    rollout_steps: 128
    batch_size: 32
    logger: wandb

  CartPole-v1:
    algo_name: ppo_penalty
    max_timesteps: 300000
    actor_lr: 1.0e-3
    critic_lr: 1.0e-2
    buffer_size: 128
    rollout_steps: 128
    batch_size: 32
    logger: wandb

sac:
  CartPole-v0:
    algo_name: sac
    max_timesteps: 20000
    actor_lr: 3.0e-4
    critic_lr: 3.0e-4
    alpha_lr: 3.0e-4
    buffer_size: 10000
    batch_size: 64
    logger: tensorboard
  CartPole-v1:
    algo_name: sac
    max_timesteps: 500000
    actor_lr: 3.0e-4
    critic_lr: 3.0e-4
    alpha_lr: 3.0e-3
    buffer_size: 10000
    batch_size: 64
    logger: wandb

td3:
  Pendulum-v1:
    algo_name: td3
    actor_lr: 1.0e-3
    critic_lr: 1.0e-3
    max_timesteps: 100000
    buffer_size: 20000
    target_update_frequency: 1
    soft_update_tau: 0.01
    train_frequency: 10
    gradient_steps: 2
    batch_size: 128
    logger: wandb

saccon:
  Hopper-v4:
    algo_name: saccon
    actor_lr: 3.0e-4
    critic_lr: 1.0e-3
    alpha_lr: 3.0e-4
    max_timesteps: 2000000
    buffer_size: 1000000
    train_frequency: 10
    gradient_steps: 2
    batch_size: 256
    logger: wandb
